### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by ThisIsTenou** [pieterlouw/caddy-net#20] opened 2019-11-18 07:06 UTC
I'm not able to install the plug in, neither via the caddy download page nor through the direct links.

**Comment by zuedev** [comment] 2019-11-24 11:40
I also cannot install this plugin, this is what `getcaddy.com` says:

```
root@tiamon ~# curl https://getcaddy.com | bash -s personal net
Downloading Caddy for linux/amd64 (personal license)...
curl: (22) The requested URL returned error: 500 
Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"
```

**Comment by etique57** [comment] 2019-12-30 15:56
Same for me.

**Comment by benma** [comment] 2020-01-11 13:28
Bump. Maybe it has to do with:

```
github.com/pieterlouw/caddy-net@v0.1.5/caddynet/netserver/tls.go:77:48: too many arguments in call to certCache.RenewManagedCertificates
	have (bool)
	want ()
```

**Comment by hscells** [comment] 2020-02-03 05:48
@pieterlouw now that this has been resolved in #21 what now has to happen for builds to resume on https://caddyserver.com/v1/download?

**Comment by pieterlouw** [comment] 2020-02-03 06:05
> @pieterlouw now that this has been resolved in #21 what now has to happen for builds to resume on https://caddyserver.com/v1/download?

Hi @hscells , it should be backwards compatible.

**Comment by hscells** [comment] 2020-02-03 22:24
Once it has been confirmed that #21 indeed fixes the problem, I believe the plugin must be updated through the caddy developer account: https://github.com/caddyserver/caddy/wiki/Publishing-a-Plugin-to-the-Download-Page#updating-your-plugin

However, it looks like #22 might be an even more recent version of the bug reported in this issue (and consequently resolved in #21)

**Comment by hscells** [comment] 2020-02-06 03:46
@pieterlouw just wondering if there has been any progress made towards this?

How would it be possible to use your plugin in caddy without downloading from the website?

**Comment by streaps** [comment] 2020-03-03 14:41
I have the same problem. https://caddyserver.com/v1/download still returns an error, if you build Caddy with the net plugin.

**Comment by pieterlouw** [comment] 2020-04-08 07:20
Hi,

New version of the plugin has been uploaded , please try again.

**Closed as completed by pieterlouw** 2020-04-08 07:20 UTC
